import { readFileSync, readdirSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import assert from 'node:assert/strict';
import ts from 'typescript';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const sqlite=new DatabaseSync(':memory:');
for (const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()) sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
let currentUser=null;
const db={prepare(sql){let values=[];return {bind(...v){values=v;return this;},async first(){return sqlite.prepare(sql).get(...values)||null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:r.changes}};}};},async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
function load(file,mocks={}){const js=ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('require','exports',js)(name=>name in mocks?mocks[name]:require(name),exports);return exports;}
const model=load('lib/portal-model.ts');
const validation=load('lib/validation.ts',{'./portal-model':model});
const api=load('app/api/portal/route.ts',{'@/lib/db':{database:()=>db,organizerEmails:()=>['organizer@example.test']},'@/lib/validation':validation});
const user=(id,email)=>({userId:id,email,displayName:id,fullName:id});
const request=(body,origin='https://assembly.test')=>new Request('https://assembly.test/api/portal',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const get=async(q='')=>(await api.GET(new Request('https://assembly.test/api/portal'+q)));
const send=async(body,status=200)=>{const r=await api.POST(request(body));assert.equal(r.status,status,JSON.stringify(await r.clone().json()));return r.json();};
const base={action:'save',type:'hacker',name:'Applicant',school:'School',skills:'Python',motivation:'Learn by building',experience:'Made a parser',availability:'',details:{firstName:'Test',lastName:'Applicant',gender:'Prefer not to say',ethnicity:'Prefer not to say',birthdate:'2000-01-01',graduationYear:'2030'},version:0,submit:false};
assert.equal((await get()).status,200);assert.equal((await (await get()).json()).me,null);
await send(base,401);
currentUser=user('alice','alice@example.test');
assert.equal((await api.POST(request(base,'https://evil.test'))).status,403);
assert.equal((await get('?view=organizer')).status,403);
await send({...base,submit:true,motivation:''},400);
await send({...base,type:'mentor',submit:true},400);
const draft=await send(base);
await send(base,409);
const submitted=await send({...base,version:1,submit:true});
await send({...base,version:2},409);
const mentor=await send({...base,type:'mentor',availability:'4–8 hours',submit:true});
assert.equal((await (await get()).json()).applications.length,2);
currentUser=user('bob','bob@example.test');
assert.equal((await (await get()).json()).applications.length,0);
await send(base);
await send({action:'review',id:draft.id,motivation:5,experience:4,contribution:4,status:'accepted',notes:'private'},403);
currentUser=user('organizer','organizer@example.test');
let queue=await (await get('?view=organizer')).json();
assert.equal(queue.applications.length,2,'Draft is private');
assert.ok(!('name' in queue.applications[0]));assert.ok(!('user_id' in queue.applications[0]));assert.ok(!('school' in queue.applications[0]));
assert.ok('name' in (await (await get('?view=organizer&blind=false')).json()).applications[0]);
await send({action:'review',id:submitted.id,motivation:6,experience:4,contribution:4,status:'accepted',notes:'private'},400);
await send({action:'review',id:submitted.id,motivation:5,experience:4,contribution:4,status:'accepted',notes:'private'});
await send({action:'review',id:submitted.id,motivation:4,experience:4,contribution:4,status:'waitlisted',notes:'updated'});
queue=await (await get('?view=organizer')).json();
const scored=queue.applications.find(a=>a.id===submitted.id);assert.equal(scored.score,12);assert.equal(scored.review_count,1);
const own=await send({...base,submit:true});
await send({action:'review',id:own.id,motivation:5,experience:4,contribution:4,status:'accepted',notes:''},403);
await send({action:'seed'});await send({action:'seed'});
assert.equal((await (await get('?view=organizer')).json()).applications.length,6,'Sample seeding is idempotent');
currentUser=user('alice','alice@example.test');
const mine=await (await get()).json();assert.equal(mine.applications.find(a=>a.id===submitted.id).status,'waitlisted');assert.equal(mine.events.length,2);assert.equal(mine.reviews.length,0);
await send({action:'seed'},403);
await send({action:'role',type:'organizer'},400);
await send({action:'role',type:'judge'});
assert.equal((await (await get()).json()).me.accountType,'judge');
await send({...base,type:'judge',submit:true,availability:''},400);
await send({...base,type:'judge',submit:true,availability:'2–4 hours',details:{...base.details,birthdate:'2009-01-01'}},400);
await send({...base,type:'judge',submit:true,availability:'2–4 hours',details:{...base.details,birthdate:'2000-02-30'}},400);
const judge=await send({...base,type:'judge',submit:true,availability:'2–4 hours'});
await send({...base,type:'volunteer',submit:true,availability:'Full weekend'});
assert.equal((await (await get()).json()).applications.length,4);
currentUser=user('organizer','organizer@example.test');
const unblinded=await (await get('?view=organizer&blind=false')).json();
assert.ok(unblinded.applications.every(a=>!('details_json' in a)),'Demographics excluded even with blind mode off');
await send({action:'review',id:judge.id,motivation:4,experience:4,contribution:4,status:'accepted',notes:''});
currentUser=user('bob','bob@example.test');
await send({action:'rsvp',id:judge.id,response:'confirmed'},409);
currentUser=user('alice','alice@example.test');
await send({action:'rsvp',id:submitted.id,response:'confirmed'},409);
await send({action:'rsvp',id:judge.id,response:'confirmed'});
await send({action:'rsvp',id:judge.id,response:'confirmed'},409);
const confirmed=await (await get()).json();
assert.equal(confirmed.applications.find(a=>a.id===judge.id).status,'confirmed');
assert.equal(confirmed.events.filter(e=>e.application_id===judge.id&&e.status==='confirmed').length,1);
currentUser=user('organizer','organizer@example.test');
await send({action:'review',id:judge.id,motivation:4,experience:4,contribution:4,status:'rejected',notes:''},409);

console.log('PASS: authentication, CSRF, ownership, all four roles, saved account selection, birthdate validation, demographic privacy, attendance confirmation, required fields, draft conflicts, submission locks, blind review, grading, private notes, status timeline, self-review prevention, and idempotent samples.');
sqlite.close();
